-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 21:40:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `cpf` BIGINT NULL,
  `birthDate` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `registration_employee` INT NOT NULL,
  `password` VARCHAR(50) NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idEmployee`, `Person_idPerson`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  UNIQUE INDEX `registration_employee_UNIQUE` (`registration_employee` ASC) VISIBLE,
  INDEX `fk_Employee_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_Client_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `public_place` VARCHAR(30) NULL,
  `streetName` VARCHAR(100) NULL,
  `neighborhood` VARCHAR(50) NULL,
  `complement` VARCHAR(50) NULL,
  `numberOfStreet` INT NULL,
  `zipCode` BIGINT NULL,
  `city` VARCHAR(50) NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `public_place_UNIQUE` (`public_place` ASC) VISIBLE,
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Count`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Count` (
  `idCount` INT NOT NULL AUTO_INCREMENT,
  `balance` FLOAT NULL,
  `financing` BINARY NULL,
  ` debitPerMonth` FLOAT NULL,
  PRIMARY KEY (`idCount`),
  UNIQUE INDEX `idCount_UNIQUE` (`idCount` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `function` VARCHAR(50) NULL,
  `salary` FLOAT NULL,
  PRIMARY KEY (`idSector`),
  UNIQUE INDEX `idSector_UNIQUE` (`idSector` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonXAddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonXAddress` (
  `Person_idPerson` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`Person_idPerson`, `Address_idAddress`),
  INDEX `fk_Person_has_Address_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  INDEX `fk_Person_has_Address_Person_idx` (`Person_idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Person_has_Address_Person`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Address_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeXSector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeXSector` (
  `Employee_idEmployee` INT NOT NULL,
  `Employee_Person_idPerson` INT NOT NULL,
  `Sector_idSector` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`, `Employee_Person_idPerson`, `Sector_idSector`),
  INDEX `fk_Employee_has_Sector_Sector1_idx` (`Sector_idSector` ASC) VISIBLE,
  INDEX `fk_Employee_has_Sector_Employee1_idx` (`Employee_idEmployee` ASC, `Employee_Person_idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Sector_Employee1`
    FOREIGN KEY (`Employee_idEmployee` , `Employee_Person_idPerson`)
    REFERENCES `mydb`.`Employee` (`idEmployee` , `Person_idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Sector_Sector1`
    FOREIGN KEY (`Sector_idSector`)
    REFERENCES `mydb`.`Sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClientXCount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClientXCount` (
  `idClient` INT NOT NULL,
  `idCount` INT NOT NULL,
  PRIMARY KEY (`idClient`, `idCount`),
  INDEX `fk_Client_has_Count_Count1_idx` (`idCount` ASC) VISIBLE,
  INDEX `fk_Client_has_Count_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Count_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Count_Count1`
    FOREIGN KEY (`idCount`)
    REFERENCES `mydb`.`Count` (`idCount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
