-- MySQL Script generated by MySQL Workbench
-- Mon Aug  8 19:48:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `InvestMais` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InvestMais` DEFAULT CHARACTER SET utf8 ;
USE `InvestMais` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `public_place` VARCHAR(30) NULL,
  `streetName` VARCHAR(100) NULL,
  `neighborhood` VARCHAR(50) NULL,
  `complement` VARCHAR(50) NULL,
  `numberOfStreet` INT NULL,
  `zipCode` BIGINT NULL,
  `city` VARCHAR(50) NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `public_place_UNIQUE` (`public_place` ASC) VISIBLE,
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `registration_employee` INT NOT NULL,
  `password` VARCHAR(50) NULL,
  `name` VARCHAR(80) NULL,
  `cpf` BIGINT NULL,
  `birthDate` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  UNIQUE INDEX `registration_employee_UNIQUE` (`registration_employee` ASC) VISIBLE,
  INDEX `fk_Employee_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `InvestMais`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NULL,
  `birthDate` VARCHAR(45) NULL,
  `name` VARCHAR(80) NULL,
  `email` VARCHAR(100) NULL,
  `cpf` BIGINT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Client_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `InvestMais`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Count`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`Count` (
  `idCount` INT NOT NULL AUTO_INCREMENT,
  `balance` FLOAT NULL,
  `financing` BINARY NULL,
  ` debitPerMonth` FLOAT NULL,
  PRIMARY KEY (`idCount`),
  UNIQUE INDEX `idCount_UNIQUE` (`idCount` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`Sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `function` VARCHAR(50) NULL,
  `salary` FLOAT NULL,
  PRIMARY KEY (`idSector`),
  UNIQUE INDEX `idSector_UNIQUE` (`idSector` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeXSector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`EmployeeXSector` (
  `Employee_idEmployee` INT NOT NULL,
  `Employee_Person_idPerson` INT NOT NULL,
  `Sector_idSector` INT NOT NULL,
  PRIMARY KEY (`Employee_idEmployee`, `Employee_Person_idPerson`, `Sector_idSector`),
  INDEX `fk_Employee_has_Sector_Sector1_idx` (`Sector_idSector` ASC) VISIBLE,
  INDEX `fk_Employee_has_Sector_Employee1_idx` (`Employee_idEmployee` ASC, `Employee_Person_idPerson` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Sector_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `InvestMais`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Sector_Sector1`
    FOREIGN KEY (`Sector_idSector`)
    REFERENCES `InvestMais`.`Sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClientXCount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InvestMais`.`ClientXCount` (
  `idClient` INT NOT NULL,
  `idCount` INT NOT NULL,
  PRIMARY KEY (`idClient`, `idCount`),
  INDEX `fk_Client_has_Count_Count1_idx` (`idCount` ASC) VISIBLE,
  INDEX `fk_Client_has_Count_Client1_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Count_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `InvestMais`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Count_Count1`
    FOREIGN KEY (`idCount`)
    REFERENCES `InvestMais`.`Count` (`idCount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
